- name: Download binary
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: "{{ folder_tmp }}/vault_{{ vault_version }}_linux_amd64.zip"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755
    checksum: "{{ vault_checksum }}"
  register: vault_download

- name: "Unzip vault archive"
  ansible.builtin.unarchive:
    src: "{{ vault_download.dest }}"
    dest: "{{ vault_binary_folder }}"
    copy: no
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755

- name: Set vault capabilities
  community.general.capabilities:
    path: "{{ vault_binary_folder }}/{{ vault_binary }}"
    capability: cap_ipc_lock=ep
    state: present