- name: "Creating vault user group '{{ vault_group }}'"
  ansible.builtin.group:
    name: "{{ vault_group }}"
  become: true

- name: "Creating vault user '{{ vault_user }}'"
  ansible.builtin.user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: /sbin/nologin
    comment: "vault nologin User"
    createhome: "no"
    state: present

- name: Create vault settings folder
  ansible.builtin.file:
    path: "{{ vault_config_folder }}"
    state: directory
    owner: root
    group: root

- name: Create vault data folder
  ansible.builtin.file:
    path: "{{ vault_data_folder }}"
    state: directory
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: Create unseal directories
  ansible.builtin.file:
    path: "{{ vault_config_folder }}/{{ vault_keys_folder }}"
    state: directory
  delegate_to: localhost

- name: Create root key directories
  ansible.builtin.file:
    path: "{{ vault_config_folder }}/{{ vault_root_token_folder }}"
    state: directory
  delegate_to: localhost

- name: Install required packages
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ vault_install_prerequisites }}"
  become: yes