- name: Get vault status
  ansible.builtin.shell: vault operator init -status
  environment:
    VAULT_ADDR: "{{ vault_address }}:{{ vault_port }}"
  register: vault_init_status
  failed_when: vault_init_status.rc not in [ 0, 2 ]

- name: Reset Vault
  include_tasks: reset.yml
  when: vault_init_status.stdout == "Vault is initialized"
