- name: Get vault status
  ansible.builtin.shell: vault operator init -status
  environment:
    VAULT_ADDR: "{{ vault_address }}:{{ vault_port }}"
  register: vault_init_status
  failed_when: vault_init_status.rc not in [ 0, 2 ]

- name: Stop Vault
  ansible.builtin.systemd:
    name: vault
    state: stopped
    enabled: yes
  when: vault_init_status.stdout == "Vault is initialized"

- name: Find all files
  ansible.builtin.find:
    paths: "{{ vault_data_folder }}/data"
    recurse: yes
    use_regex: no
    patterns: "*"
  register: files_to_delete
  when: vault_init_status.stdout == "Vault is initialized"

- name: Remove file glob
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  no_log: true
  with_items: "{{ files_to_delete.files }}"
  when: vault_init_status.stdout == "Vault is initialized"

- name: Start Vault
  ansible.builtin.systemd:
    name: vault
    state: started
    enabled: yes
  when: vault_init_status.stdout == "Vault is initialized"